Imported and modified the latest DPG code for single pi0 simulation

diff --git a/protons/single-pi0-production/simulation/Makefile b/protons/single-pi0-production/simulation/Makefile
--- a/protons/single-pi0-production/simulation/Makefile
+++ b/protons/single-pi0-production/simulation/Makefile
@@ -1,28 +1,36 @@
-SEED=1123444
+RUN     = 117222
+NEVENTS = 1
+MODE    = "sim,rec"
+EXTRA   = "--bmin 14.5 --bmax 15.5 --pthardbin 1"
 
-MHOME=/alice/cern.ch/user/o/okovalen
-REPO=single-pi0-production
-OUTPUT=$(MHOME)/$(REPO)/output/$(SEED)
-FILES = Config.C CreateAOD.C generate.jdl merge.jdl merge.sh single-pion.sh rec.C sim.C tag.C
+OBJECTS = Pythia6_Perugia2011 \
+	  Pythia8_Monash2013 \
+	  Pythia8Jets_Monash2013 \
+	  Phojet \
+	  EPOSLHC \
+	  Hijing
 
-test:
-	./single-pion.sh
+SOURCEDIR   = $(ALIDPG_ROOT)/MC/CustomGenerators/
+SOURCES    := $(shell find $(SOURCEDIR) -name '*.C')
+OBJECTS    += $(SOURCES:$(SOURCEDIR)%.C=%)
 
-upload:
-	# -alien_rmdir $(MHOME)/$(REPO)
-	alien_mkdir -p $(MHOME)/$(REPO)/
-	$(foreach file, $(FILES), alien_cp -n $(file) alien:$(MHOME)/$(REPO)/;)
+all: $(OBJECTS)
 
-download:
-	mkdir -p results 
-	for run in $$(alien_ls /$(OUTPUT) | grep .[0-9]*); do alien_cp alien://$(OUTPUT)/$$run/generated.root results/$$run.root; done	
-	rm -rf generated.root
-	hadd generated.root results/*.root
-	rm -rf results
-	echo -e "\x07
+$(OBJECTS): OCDBsim.root OCDBrec.root
+	$(eval GEN := $(subst /,:,$@))
+	@echo "=== Running test simulation run ${RUN} with generator ${GEN} ==="
+	@mkdir -p $@
+	@ln -s $(PWD)/OCDBsim.root $@/.
+	@ln -s $(PWD)/OCDBrec.root $@/.
+	@cd $@ && $(ALIDPG_ROOT)/bin/aliroot_dpgsim.sh --run ${RUN} --generator ${GEN} --mode ${MODE} --nevents ${NEVENTS} ${EXTRA} &> dpgsim.log && echo " [SUCCESS] Running test simulation run ${RUN} with generator ${GEN}" || echo " [FAILURE] Running test simulation run ${RUN} with generator ${GEN}"
 
+OCDBsim.root:
+	@echo "=== Running OCDB snapshot creation for run ${RUN} ==="
+	@$(ALIDPG_ROOT)/bin/aliroot_dpgsim.sh --run ${RUN} --mode ocdb &> snapshot.log && echo " [SUCCESS] Running OCDB snapshot creation for run ${RUN}" || echo " [FAILURE] Running OCDB snapshot creation for run ${RUN}"
 
+OCDBrec.root:
+	@echo "=== Running OCDB snapshot creation for run ${RUN} ==="
+	@$(ALIDPG_ROOT)/bin/aliroot_dpgsim.sh --run ${RUN} --mode ocdb &> snapshot.log && echo " [SUCCESS] Running OCDB snapshot creation for run ${RUN}" || echo " [FAILURE] Running OCDB snapshot creation for run ${RUN}"
 
 clean:
-	rm -rf tmp_results
-	rm -rf *.root *~ *.log *.so *.d *.ps GRP *.dat *.txt *.inp
+	rm -rf *~ *.log validation_error.message *.xml $(OBJECTS)
